import { Extension, ExtensionContext } from 'canvas-ide-core';
import { ViewProvider } from 'canvas-ide-core';

export default class KitchenSinkExtension implements Extension {
    public id = 'kitchen-sink';
    public name = 'Kitchen Sink Extension';
    public version = '1.0.0';

    public async activate(context: ExtensionContext): Promise<void> {
        const ide = context.ide;

        // 1. Register Configuration Settings
        context.registerConfiguration({
            id: 'kitchensink',
            title: 'Kitchen Sink Settings',
            properties: {
                'kitchensink.showToasts': {
                    type: 'boolean',
                    default: true,
                    description: 'Show toasts when events occur.'
                },
                'kitchensink.themeColor': {
                    type: 'enum',
                    default: 'blue',
                    enum: ['blue', 'purple', 'green'],
                    description: 'Favorite color for the Kitchen Sink UI.'
                }
            }
        });

        // 2. Register Commands
        const helloWorldCmd = {
            id: 'kitchensink.helloWorld',
            label: 'Kitchen Sink: Hello World',
            keybinding: 'Ctrl+Shift+H',
            handler: () => {
                ide.notifications.notify({
                    message: 'Hello from the Kitchen Sink!',
                    severity: 'success',
                    source: { id: this.id, label: this.name },
                    timeout: 3000
                });
            }
        };
        ide.commands.register(helloWorldCmd);
        context.subscriptions.push({ dispose: () => ide.commands.unregister(helloWorldCmd.id) });

        const interactiveCmd = {
            id: 'kitchensink.interactive',
            label: 'Kitchen Sink: Interactive Dialogs',
            handler: async () => {
                // Quick Pick Example
                const choice = await ide.dialogs.showQuickPick([
                    { id: 'apple', label: 'Apple', icon: 'fas fa-apple-alt' },
                    { id: 'banana', label: 'Banana', icon: 'fas fa-lemon' } // Close enough icon!
                ], { placeholder: 'Pick a fruit...' });

                if (!choice) return;

                // Prompt Example
                const name = await ide.dialogs.prompt(`You picked ${choice.label}. What is your name?`, {
                    title: 'Name Entry',
                    placeholder: 'Enter your name'
                });

                if (!name) return;

                // Confirm Example
                const isConfirmed = await ide.dialogs.confirm(`Ready to submit your choice, ${name}?`, {
                    title: 'Final Confirmation',
                    primaryLabel: 'Submit',
                    isDestructive: false
                });

                if (isConfirmed) {
                    ide.notifications.notify(`Submission complete for ${name}.`, 'success');
                }
            }
        };
        ide.commands.register(interactiveCmd);
        context.subscriptions.push({ dispose: () => ide.commands.unregister(interactiveCmd.id) });

        const editorDemoCmd = {
            id: 'kitchensink.openVirtualFile',
            label: 'Kitchen Sink: Open Virtual File',
            handler: () => {
                // Write a virtual file using the VFS and open it
                const vfsPath = '/kitchen-sink-demo.ts';
                const content = `// Generated by Kitchen Sink\n\nexport function test() {\n    console.log("Virtual file active!");\n}\n`;

                ide.vfs.writeFile(vfsPath, content).then(() => {
                    ide.editor.openFile(vfsPath, 'kitchen-sink-demo.ts', content, 'typescript');
                }).catch(err => {
                    ide.notifications.notify(`Failed to write file: ${err.message}`, 'error');
                });
            }
        };
        ide.commands.register(editorDemoCmd);
        context.subscriptions.push({ dispose: () => ide.commands.unregister(editorDemoCmd.id) });


        // 3. Register a Custom View (Right Panel)
        const customView: ViewProvider = {
            id: 'kitchensink.sidebarView',
            name: 'Kitchen Sink View',
            resolveView: (container, disposables) => {
                // Create UI
                container.innerHTML = `
                    <div style="padding: 16px; color: var(--text-main); display: flex; flex-direction: column; gap: 12px;">
                        <h3 style="margin: 0; font-size: 14px; text-transform: uppercase; color: var(--text-muted);">Kitchen Sink Dashboard</h3>
                        <p style="font-size: 12px;">This is a custom panel contributed by the extension.</p>
                        <button id="ks-btn-toast" class="dialog-btn dialog-btn-primary">Trigger Toast</button>
                        <button id="ks-btn-dialog" class="dialog-btn dialog-btn-secondary">Show Dialog Flow</button>
                    </div>
                `;

                // Wire up events
                const btnToast = container.querySelector('#ks-btn-toast') as HTMLElement;
                const btnDialog = container.querySelector('#ks-btn-dialog') as HTMLElement;

                const onToastClick = () => ide.commands.execute('kitchensink.helloWorld');
                const onDialogClick = () => ide.commands.execute('kitchensink.interactive');

                btnToast?.addEventListener('click', onToastClick);
                btnDialog?.addEventListener('click', onDialogClick);

                // Clean up listeners when view unmounts
                disposables.push({ dispose: () => btnToast?.removeEventListener('click', onToastClick) });
                disposables.push({ dispose: () => btnDialog?.removeEventListener('click', onDialogClick) });
            }
        };
        ide.views.registerProvider('right-panel', customView);
        context.subscriptions.push({ dispose: () => ide.views.unregisterProvider('right-panel', customView.id) });

        // 4. Add Activity Bar Icon to toggle the view
        ide.activityBar.registerItem({
            id: customView.id, // Must match the ViewProvider ID
            location: 'right-panel',
            icon: 'fas fa-sink',
            title: 'Kitchen Sink',
            order: 999
        });
        context.subscriptions.push({ dispose: () => ide.activityBar.unregisterItem(customView.id) });

        // 5. Add to the Top Menu Bar
        ide.layout.header.menuBar.addMenuItem({
            id: 'kitchensink-menu',
            label: 'Kitchen Sink',
            items: [
                { id: 'ks-menu-1', label: 'Hello World', shortcut: 'Ctrl+Shift+H', onClick: () => ide.commands.execute('kitchensink.helloWorld') },
                { id: 'ks-menu-2', label: 'Interactive Flow', onClick: () => ide.commands.execute('kitchensink.interactive') },
                { id: 'ks-menu-3', label: 'Generate Virtual File', onClick: () => ide.commands.execute('kitchensink.openVirtualFile') },
            ]
        });
        // Note: The provided MenuBar API currently doesn't expose a 'removeMenuItem' method.

        // 6. Global Event Listening
        const subId = ide.commands.on('editor.tab.opened', (data: { tabId: string }) => {
            // Check the configuration registry before reacting
            if (ide.settings.get('kitchensink.showToasts')) {
                ide.notifications.setStatusMessage(`Opened: ${data.tabId}`, 2000);
            }
        });
        context.subscriptions.push({ dispose: () => ide.commands.off(subId) });

        ide.notifications.notify(`Kitchen Sink initialized!`, 'info', 3000);
    }

    public deactivate(): void {
        console.log(`Kitchen Sink deactivated. Resources are cleaned up via context.subscriptions.`);
    }
}